DELIMITER //

CREATE PROCEDURE GetTopPurchasingClient()
BEGIN
    SELECT c.ID, c.NAME, c.SURNAME, c.EMAIL, c.PURCHASES, c.CREATE_DATE, c.UPDATE_DATE
    FROM CLIENT c
    JOIN SALES s ON c.ID = s.CLIENT_ID
    GROUP BY c.ID
    ORDER BY SUM(s.QUANTITY) DESC
    LIMIT 1;
END //

DELIMITER ;
